//! Data generator only. Test assertions live in packages/circuits/src/tests/*.nr.
use crypto_lib::*;
use k256::ecdsa::{Signature, SigningKey, signature::hazmat::PrehashSigner};
use sha3::{Digest, Keccak256};
use std::{fmt::Write, fs, path::Path};

fn inputs(leaf: &LeafData, tree: &MerkleTree, index: usize, wallet: u8) -> CircuitInputs {
    let key = format!("{wallet:02x}").repeat(32);
    let recipient = "0x2222222222222222222222222222222222222222";
    let signature = sign_message(
        &key,
        &signing_message(recipient, &leaf.nullifier_seed).unwrap(),
    )
    .unwrap();
    circuit_inputs(
        leaf,
        tree,
        index,
        recipient,
        &public_key_from_private(&key).unwrap(),
        &signature,
    )
    .unwrap()
}

fn emit(output: &mut String, name: &str, value: &CircuitInputs) {
    writeln!(output, "pub fn {name}() -> Claim {{\n    Claim {{").unwrap();
    for (key, value) in serde_json::to_value(value).unwrap().as_object().unwrap() {
        // All fields are decimal strings or fixed arrays of fields/bytes.
        writeln!(
            output,
            "        {key}: {},",
            value.to_string().replace('"', "")
        )
        .unwrap();
    }
    writeln!(output, "    }}\n}}\n").unwrap();
}

fn resign(value: &mut CircuitInputs) {
    let message = hash_children(&value.recipient, &value.nullifier_seed).unwrap();
    let signature = sign_message(&"01".repeat(32), &field_to_bytes(&message).unwrap()).unwrap();
    value.signature = hex::decode(&signature[2..130]).unwrap();
}

fn main() {
    let public_key = public_key_from_private(&"01".repeat(32)).unwrap();
    let address = public_key_address(&public_key).unwrap();
    let mut leaf = leaf_from_phrase(&address, "circuit-test-secret", "0x1234", "0").unwrap();
    leaf.tier_key = derive_tier_key("42", "9", &nullifier_hash(&leaf).unwrap()).unwrap();
    let tree = build_tree(&[leaf.clone()]).unwrap();
    let valid = inputs(&leaf, &tree, 0, 1);
    let mut output = String::from(
        "// Generated by crypto-lib/examples/noir_fixtures.rs. Do not edit by hand.\nuse super::Claim;\n\n",
    );
    emit(&mut output, "valid", &valid);
    writeln!(
        output,
        "pub fn owner_address() -> Field {{ {} }}",
        address_to_field(&address).unwrap()
    )
    .unwrap();
    writeln!(
        output,
        "pub fn leaf_hash() -> Field {{ {} }}",
        hash_leaf(&leaf).unwrap()
    )
    .unwrap();
    writeln!(
        output,
        "pub fn message() -> [u8; 32] {{ {:?} }}",
        signing_message(
            "0x2222222222222222222222222222222222222222",
            &leaf.nullifier_seed
        )
        .unwrap()
    )
    .unwrap();

    let outsider = LeafData {
        address: public_key_address(&public_key_from_private(&"02".repeat(32)).unwrap()).unwrap(),
        ..leaf.clone()
    };
    emit(
        &mut output,
        "outsider",
        &inputs(&outsider, &build_tree(&[outsider.clone()]).unwrap(), 0, 2),
    );
    for (name, value) in [
        ("zero_fields", "0"),
        (
            "maximum_fields",
            "0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000000",
        ),
    ] {
        let boundary = LeafData {
            secret: value.into(),
            nullifier_seed: value.into(),
            tier_key: value.into(),
            ..leaf.clone()
        };
        emit(
            &mut output,
            name,
            &inputs(&boundary, &build_tree(&[boundary.clone()]).unwrap(), 0, 1),
        );
    }
    let changed = LeafData {
        nullifier_seed: "999".into(),
        ..leaf.clone()
    };
    emit(
        &mut output,
        "changed_seed",
        &inputs(&changed, &build_tree(&[changed.clone()]).unwrap(), 0, 1),
    );
    for (name, recipient) in [
        (
            "new_recipient",
            "0x3333333333333333333333333333333333333333",
        ),
        ("zero_recipient", "0"),
        (
            "max_address_recipient",
            "0xffffffffffffffffffffffffffffffffffffffff",
        ),
        (
            "wide_recipient",
            "0x10000000000000000000000000000000000000000",
        ),
        ("same_wallet_recipient", &address),
    ] {
        let mut value = valid.clone();
        value.recipient = normalize_field(recipient).unwrap();
        resign(&mut value);
        emit(&mut output, name, &value);
    }
    let mut different = filler_leaf(1).unwrap();
    different.secret = "123".into();
    emit(
        &mut output,
        "different_root",
        &inputs(
            &leaf,
            &build_tree(&[leaf.clone(), different]).unwrap(),
            0,
            1,
        ),
    );
    let arbitrary_tier = LeafData {
        tier_key: "424242".into(),
        ..leaf.clone()
    };
    emit(
        &mut output,
        "arbitrary_tier",
        &inputs(
            &arbitrary_tier,
            &build_tree(&[arbitrary_tier.clone()]).unwrap(),
            0,
            1,
        ),
    );

    let message = signing_message(
        "0x2222222222222222222222222222222222222222",
        &leaf.nullifier_seed,
    )
    .unwrap();
    let signing_key = SigningKey::from_slice(&[1; 32]).unwrap();
    let raw: Signature = signing_key.sign_prehash(&message).unwrap();
    let text = format!("0x{}", hex::encode(message));
    let prefixed = format!("\x19Ethereum Signed Message:\n{}{text}", text.len());
    let as_text: Signature = signing_key
        .sign_prehash(&Keccak256::digest(prefixed.as_bytes()))
        .unwrap();
    let mut little = message;
    little.reverse();
    for (name, signature) in [
        ("raw_signature", raw.to_bytes().to_vec()),
        ("text_signature", as_text.to_bytes().to_vec()),
        (
            "little_endian_signature",
            hex::decode(&sign_message(&"01".repeat(32), &little).unwrap()[2..130]).unwrap(),
        ),
    ] {
        writeln!(output, "pub fn {name}() -> [u8; 64] {{ {signature:?} }}").unwrap();
    }
    // A single full tree, with a distinct registered secret at every position.
    let leaves = (0..LEAF_COUNT)
        .map(|i| LeafData {
            secret: (i + 1).to_string(),
            ..leaf.clone()
        })
        .collect::<Vec<_>>();
    let full_tree = build_tree(&leaves).unwrap();
    writeln!(
        output,
        "pub fn full_tree_root() -> Field {{ {} }}",
        full_tree.root()
    )
    .unwrap();
    writeln!(
        output,
        "pub fn full_tree_path(index: u32) -> [Field; 8] {{\n    let paths: [[Field; 8]; 256] = ["
    )
    .unwrap();
    for i in 0..LEAF_COUNT {
        writeln!(
            output,
            "        [{}],",
            full_tree.merkle_path(i).unwrap().join(", ")
        )
        .unwrap();
    }
    writeln!(output, "    ];\n    paths[index]\n}}").unwrap();
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../circuits/src/tests/fixtures.nr");
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(path, output).unwrap();
}
